server:
  port: 8006
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn-es-hotel?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://159.75.251.227:9200
  rabbitmq:
    host: 159.75.251.227
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ch.hotelDemo.pojo